Update codeql.yml

diff --git a/.github/workflows/codeql.yml b/.github/workflows/codeql.yml
--- a/.github/workflows/codeql.yml
+++ b/.github/workflows/codeql.yml
@@ -5,7 +5,7 @@ on:
     branches: [ "add-license-1","add-license-2" ]
   pull_request:
     # The branches below must be a subset of the branches above
-    branches: [ "add-license-1","add-license-2" ]
+    branches: [ "add-license-1" ]
   schedule:
     - cron: '44 2 * * 4'
 
@@ -42,6 +42,19 @@ jobs:
       uses: github/codeql-action/autobuild@v2
 
     - name: Perform CodeQL Analysis
+      id: codeql
       uses: github/codeql-action/analyze@v2
       with:
         category: "/language:${{matrix.language}}"
+
+    - name: Check for critical issues
+      run: |
+        # Retrieve the number of critical issues from the CodeQL analysis results
+        critical_issues=$(jq '.annotations[] | select(.properties.severity == "critical")' "${{ steps.codeql.outputs.codeql-results }}")
+
+        # Fail the build if there are critical issues
+        if [[ $critical_issues ]]; then
+          echo "Critical issues detected:"
+          echo "$critical_issues"
+          exit 1
+        fi
